### ISSUE TITLE
How does user_sources.py work?

### ISSUE THREAD

**Issue by khurshid-alam** [KarolBedkowski/kupfer-contrib#1]
How does it work? Can you explain?

Lets say I have many vcard files in a folder (~/contacts),

A1.ics, B1.ics, C1.ics which should open with evolution by default.

I want to search these files from kupfer? How can it be done?

**Comment by KarolBedkowski** [comment]
user_sources plugin works in two modes (for each source configured in ~/.config/kupfer/user_sources.cfg) - launch configured command and read it output or load text file. Look at user_source.py - there is sample config on top.

In your case, I think, you should create some script that load *.ics files, parse and return use full data. But in this version this plugin is very simple - you can create only text/url/file leaves. You probably expect something like EmailContact - but this complicated object and there is no simple way to use it with user_sources.

You may try create whole own plugin for this - i.e. based on clawsmail.py
